### ISSUE TITLE
Empty wiki "Backend" page

### ISSUE THREAD

**Issue by NatrixAeria** [squirrel-labs/ratatosk#10]
the wiki page for [Backend](https://github.com/TrueDoctor/DiscoBot/wiki/Backend) is nearly empty. Please add some documentation, so that everyone can see what you do and what you have done. A documentation is very important for a healthy project.

**Comment by TrueDoctor** [comment]
We have some basic information about the different parts of the Project with references to further reading.
For more in-depth documentation please consult [doc.rask.rocks](https://doc.rask.rocks)
