### ISSUE TITLE
obsolete path for fake-favicon

### ISSUE THREAD

**Issue by vlle1** [squirrel-labs/ratatosk#106]
correct path: 
https://github.com/squirrel-labs/GameLobby/blob/master/src/resources/icon_skribbl.png
js console output:
GET https://github.com/squirrel-labs/GameLobby/blob/master/WebInterface/dist/ressources/icon_ratatosk.png?raw=true 404 (Not Found)

**Comment by TrueDoctor** [comment]
The nginx configuration was at fault, it should be fixed now
