### ISSUE TITLE
Explain how to use Issues and Projects

### ISSUE THREAD

**Issue by TrueDoctor** [squirrel-labs/ratatosk#11]

**Comment by Ma27** [comment]
I'm currently writing a proposal regarding how we can use git in the future. If that's okay for you, I'd also include a section about Issues/Projects :)

**Comment by TrueDoctor** [comment]
https://github.com/TrueDoctor/ratatosk/wiki/%5BDraft%5D-GIT-Branching-Development-Vorschlag

**Comment by Ma27** [comment]
Thx for the reminder, will improve the stuff tomorrow and bother you on Discord with the results :)

**Comment by TrueDoctor** [comment]
We have started to adopt some suggestions mentioned in https://github.com/TrueDoctor/ratatosk/wiki/%5BDraft%5D-GIT-Branching-Development-Vorschlag
and improved our git hygiene.
I think the scope of this issue is well fulfilled.
Thank a lot @Ma27 for all your work
