### ISSUE TITLE
Rename crates 

### ISSUE THREAD

**Issue by TrueDoctor** [squirrel-labs/ratatosk#15]
Rename crates to for example replace webhogg with ratatosk/rask

**Comment by Ma27** [comment]
While we're at this, we should also incorporate a consistent naming schema (e.g. dashes vs. underscores, `{rask,ratatosk}_` as prefix?, etc.)

**Comment by konsumlamm** [comment]
Regarding dashes vs underscores, the convention seems to be to use hyphens for separating words in crate names, so i think we should stick to that.

**Comment by konsumlamm** [comment]
Committed refactor. Build failing, apparently because the names have to be updated in the CI build script.

**Comment by TrueDoctor** [comment]
renaming done reopen if it should come up again
