### ISSUE TITLE
Investigate if there's a secure way to host Jenkinsfiles in Git

### ISSUE THREAD

**Issue by Ma27** [squirrel-labs/ratatosk#21]
Although the current Jenkins setup of @TrueDoctor is pretty nice, I'd propose to incorporate a [Jenkinsfile](https://jenkins.io/doc/book/pipeline/jenkinsfile/) into our repository for the following reasons:

* We can track our config with Git and use different configs on different branches (e.g. #14 causes a lot of verbose notifications because I changed several parts of our build system).
* It's easier to know what's going on: especially when being new to Jenkins, their UI can be pretty confusing. The config file is way simpler to read, better to reach (e.g. when hacking offfline on the proejct) and easier to understand.

However we need to ensure that Jenkins prevents any edits from any user (e.g. a third-party contributor with harmful intentions may file a PR with a broken Jenkinsfile). Although we run all builds in a VM on `jenkins.kobert.dev`, we should check if there's some kind of plugin which only allows modifications in Jenkinsfiles from "trusted" users.

*(also shamelessly adding @TrueDoctor as co-assignee as this affects services hosted on his infra)*

**Comment by TrueDoctor** [comment]
We cloud restrict the jenkins builds to certain branches or users with push access

**Comment by Ma27** [comment]
So I just found features from Jenkins to restrict builds to whitelisted repositories which isn't something I'm too happy about as I'd prefer to give external contributors an easy way of feedback as well.

As I didn't find a suitable plugin, I'd play around with Jenkins (probably a test instance later) to hack something suitable together :)
Internet is pretty poor though because of vacation :D

**Comment by TrueDoctor** [comment]
Now longer relevant due to the switch to drone
