### ISSUE TITLE
Remove unnecessary wasm instructions to reduce binary size

### ISSUE THREAD

**Issue by TrueDoctor** [squirrel-labs/ratatosk#55]
Remove the unreachable instruction to reduce the resulting binary size

**Comment by TrueDoctor** [comment]
Good thing we didn't deprecate the atomify script yet

**Comment by konsumlamm** [comment]
This would also have the advantage that the program can't crash anymore.

**Comment by NatrixAeria** [comment]
Sounds reasonable. I wonder why I didn't have this idea before…

**Comment by Ma27** [comment]
@TrueDoctor it's fairly likely that I forgot an important detail - but can you provide some context here, please? (which crate are we talking about? and were there any reasons to add those in the first place?)

**Comment by NatrixAeria** [comment]
Of course. `wasm` has an `unreachable`-Instruction that causes an application to crash if it is reached, so for stability we should remove those.
That would also reduce the size of the binary executable.
As wasm does not have any kind of undefined behaviour, this would also be compatible with the rust safety philosophy.

**Comment by NatrixAeria** [comment]
I would also suggest to replace all `Atomic.store`- and `Atomic.load` with normal `store` and `load` for a performance boost, since read-write-collisions/racing-conditions are very rare.

**Comment by TrueDoctor** [comment]
closing this extremly valuable issue for fairly obvious reasons
