### ISSUE TITLE
Generate rustdoc during the CI process

### ISSUE THREAD

**Issue by TrueDoctor** [squirrel-labs/ratatosk#6]

**Comment by Ma27** [comment]
As we don't have a Jenkinsfile in our repo - do we need to do this in the jobset's configuration on the server? Or would it make more sense to somehow include this in the cargo build process (a.k.a. produce docs during the build by default and somehow deploy the docs from the CI somewhere on `kobert.dev`?)

**Comment by TrueDoctor** [comment]
As of now, I have integrated the documentation into the deployment process. I have a seperate webhook, that builds the current changes and publishes them to my website. (kobert.dev/ratatosk/[branch]{/doc})
But is currently down due to the renaming of the repo. You should have the rights to check the server configuration as well. It might be smarter to integrate it there

**Comment by TrueDoctor** [comment]
Doc now lives here -> [Documentation](https://doc.rask.rocks)
