### ISSUE TITLE
Add release mode for wasm code

### ISSUE THREAD

**Issue by TrueDoctor** [squirrel-labs/ratatosk#63]
Add a release mode that:
* compiles the code with --release 
* strips the wam binary
* enables optimizations in wasm-opt
* disable heap guard (feature flag?)

**Comment by Ma27** [comment]
FYI (I can do this myself some day of course), this should be pretty simple to do with [profiles](https://github.com/sagiegurari/cargo-make#profiles) from `cargo-make`. Those automatically add a e.g. `--release` flag to cargo builds and we could detect which profile is used to perform additional optimizations where needed.
