### ISSUE TITLE
Preview broken

### ISSUE THREAD

**Issue by TrueDoctor** [squirrel-labs/ratatosk#88]
**Describe the bug**
rask.rocks crashes with a segfault

**To Reproduce**
go to rask.rocks

**Expected behavior**
preview is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/21245806/89279283-7a3c0f80-d647-11ea-9ed9-c838536b6775.png)

**Desktop (please complete the following information):**
 - OS:  Arch Linux
 - Chromium 84.0.4147.105 (Official Build) Arch Linux (64-bit)
 - Rust version rustc 1.46.0-nightly (346aec9b0 2020-07-11)

**Additional context**
might be related to #87

**Comment by NatrixAeria** [comment]
I tried it with
Chromium Version 84.0.4147.105 (Official Build) Arch Linux (64-bit)
this is the same version as your Chromium, but it works on my setup.
Did i miss something to reproduce?
Play around with the setup, change chromium versions. May it have something to do with wayland?

**Comment by TrueDoctor** [comment]
I'm running the x version now… but your right, ill try to get it to work on my side. Good to know the preview is working fine.
Might have to do something with my flags…

**Comment by TrueDoctor** [comment]
Alright chrome added some new config flags and now everything is working fine again
